version: "3.8"

networks:
  proxy:
    external: true
    name: traefik_proxy
  backend:
    driver: bridge
    internal: true
  db:
    external: true
    name: mysql57_backend

volumes:
  storage:

services:
  firefly:
    image: ezitisitis/laravel:php7.4-mysql5.7
    container_name: firefly_app
    restart: always
    command: php-fpm7.4 -F
    volumes:
      - ${APP_PATH}:/app
    networks:
      - backend
      - db
    labels:
      - "traefik.enable=false"

  nginx:
    image: nginx:latest
    container_name: firefly_nginx
    restart: always
    volumes:
      - ${APP_PATH}/public:/app/public
      - ${APP_PATH}/storage/app:/app/storage/app
      - ./config/firefly-iii/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - firefly
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.http.routers.firefly.entrypoints=http"
      - "traefik.http.routers.firefly.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.firefly.middlewares=traefik-https-redirect"
      - "traefik.http.routers.firefly-secure.entrypoints=https"
      - "traefik.http.routers.firefly-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.firefly-secure.tls.certresolver=http"
    networks:
      - proxy
      - backend